#阻止放置售货机的世界
ban-world: []

# 使用自带的硬币系统
used-coin: true

# 允许搬运器搬箱子..
used-ct-chest: true

# 只允许OP使用的经济核心
# 目前支持 economyapi，Money，playerPoints
only-use-admin-money-core: []

#是否直接给予金币物品
can-give-money-item: true

# 是否允许玩家合成空白优惠券
craft-discount: true