name: SalesmMchine
main: org.sobadfish.sales.SalesMainClass
version: 1.1.5
api:
  - 1.0.14
author: Sobadfish

depend:
  - EconomyAPI

softdepend:
  - CustomItemAPI

load: STARTUP

commands:
  sa:
    description: "给予玩家售货机物品指令"
    permission: op