name: SalesmMchine
main: org.sobadfish.sales.SalesMainClass
version: 1.5.5
api:
  - 1.0.14
author: Sobadfish


softdepend:
  - CustomItemAPI
  - EconomyAPI
  - Money
  - playerPoints

load: STARTUP

commands:
  sa:
    description: "给予玩家售货机物品指令"
    permission: op